config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :courses do
    collection do
      get 'search'
      get 'do_search'
    end
  end

  get "sessions/create"
  get "sessions/destroy"
  get 'admin/index'

  resources :users
  resources :courses
  resources :subjects
  resources :instructors

  root 'admin#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CourseCatalog</title>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="/assets/jquery.js" type="text/javascript"></script>
  <script src="/assets/jquery_ujs.js" type="text/javascript"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if !session[:user_id].nil? %>
        <li><%= link_to 'Home', user_path(session[:user_id]) %></li>
        <% else %>
        <li><%= link_to 'Home', login_path %></li>
        <% end %>
        <li><%= link_to 'Subjects', subjects_path %></li>
        <li><%= link_to 'Courses', courses_path %></li>
        <li><%= link_to 'Instructors', instructors_path %></li>
        <li><%= link_to 'Search', search_courses_path %></li>
      </ul>
      <%#= form_tag(get_results_courses_path, method: "get", class: "form") do %>
          <%#= text_field_tag :name, nil, placeholder: "Keywords for course names" %>
          <%#= submit_tag("Search", class: "btn btn-default") %>
      <%# end %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= button_to 'Logout', logout_path, method: :delete %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>

</body>
</html>